/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshQuotesRouteImport } from './routes/api/public/hooks/refresh-quotes'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshQuotesRoute =
  ApiPublicHooksRefreshQuotesRouteImport.update({
    id: '/api/public/hooks/refresh-quotes',
    path: '/api/public/hooks/refresh-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/learn': typeof LearnRoute
  '/performance': typeof PerformanceRoute
  '/publications': typeof PublicationsRoute
  '/recruiting': typeof RecruitingRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/public/hooks/refresh-quotes': typeof ApiPublicHooksRefreshQuotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/learn': typeof LearnRoute
  '/performance': typeof PerformanceRoute
  '/publications': typeof PublicationsRoute
  '/recruiting': typeof RecruitingRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/public/hooks/refresh-quotes': typeof ApiPublicHooksRefreshQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alumni': typeof AlumniRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRoute
  '/learn': typeof LearnRoute
  '/performance': typeof PerformanceRoute
  '/publications': typeof PublicationsRoute
  '/recruiting': typeof RecruitingRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/public/hooks/refresh-quotes': typeof ApiPublicHooksRefreshQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alumni'
    | '/apply'
    | '/contact'
    | '/holdings'
    | '/learn'
    | '/performance'
    | '/publications'
    | '/recruiting'
    | '/sectors'
    | '/sitemap.xml'
    | '/team'
    | '/api/public/hooks/refresh-quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alumni'
    | '/apply'
    | '/contact'
    | '/holdings'
    | '/learn'
    | '/performance'
    | '/publications'
    | '/recruiting'
    | '/sectors'
    | '/sitemap.xml'
    | '/team'
    | '/api/public/hooks/refresh-quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alumni'
    | '/apply'
    | '/contact'
    | '/holdings'
    | '/learn'
    | '/performance'
    | '/publications'
    | '/recruiting'
    | '/sectors'
    | '/sitemap.xml'
    | '/team'
    | '/api/public/hooks/refresh-quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlumniRoute: typeof AlumniRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  HoldingsRoute: typeof HoldingsRoute
  LearnRoute: typeof LearnRoute
  PerformanceRoute: typeof PerformanceRoute
  PublicationsRoute: typeof PublicationsRoute
  RecruitingRoute: typeof RecruitingRoute
  SectorsRoute: typeof SectorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  ApiPublicHooksRefreshQuotesRoute: typeof ApiPublicHooksRefreshQuotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-quotes': {
      id: '/api/public/hooks/refresh-quotes'
      path: '/api/public/hooks/refresh-quotes'
      fullPath: '/api/public/hooks/refresh-quotes'
      preLoaderRoute: typeof ApiPublicHooksRefreshQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlumniRoute: AlumniRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  HoldingsRoute: HoldingsRoute,
  LearnRoute: LearnRoute,
  PerformanceRoute: PerformanceRoute,
  PublicationsRoute: PublicationsRoute,
  RecruitingRoute: RecruitingRoute,
  SectorsRoute: SectorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  ApiPublicHooksRefreshQuotesRoute: ApiPublicHooksRefreshQuotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
