/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoldingsPerformanceRouteImport } from './routes/holdings.performance'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsPerformanceRoute = HoldingsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => HoldingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/holdings/performance': typeof HoldingsPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/holdings/performance': typeof HoldingsPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/publications': typeof PublicationsRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/holdings/performance': typeof HoldingsPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/holdings'
    | '/publications'
    | '/sectors'
    | '/team'
    | '/holdings/performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/holdings'
    | '/publications'
    | '/sectors'
    | '/team'
    | '/holdings/performance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/holdings'
    | '/publications'
    | '/sectors'
    | '/team'
    | '/holdings/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HoldingsRoute: typeof HoldingsRouteWithChildren
  PublicationsRoute: typeof PublicationsRoute
  SectorsRoute: typeof SectorsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings/performance': {
      id: '/holdings/performance'
      path: '/performance'
      fullPath: '/holdings/performance'
      preLoaderRoute: typeof HoldingsPerformanceRouteImport
      parentRoute: typeof HoldingsRoute
    }
  }
}

interface HoldingsRouteChildren {
  HoldingsPerformanceRoute: typeof HoldingsPerformanceRoute
}

const HoldingsRouteChildren: HoldingsRouteChildren = {
  HoldingsPerformanceRoute: HoldingsPerformanceRoute,
}

const HoldingsRouteWithChildren = HoldingsRoute._addFileChildren(
  HoldingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HoldingsRoute: HoldingsRouteWithChildren,
  PublicationsRoute: PublicationsRoute,
  SectorsRoute: SectorsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
